server:
  port: 8082

spring:
  application:
    name: finance-system
  
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/finance_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql8

  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: 002_finance_quinn0000000000000000
  expiration: 86400000  # 24小时，单位：毫秒

# Swagger配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.example.finance.controller

quinn:
  check:
    license:
      key: MDAxfGNfcWluZ3l1bjIwMDJAMTYzLmNvbXwyMDI1LTA0LTE3fDMwfDRpTFpvQ0tuWnZyWHJhOGFiSGZtZG9HLTMydXl0R19PMzZXS1d1QWVTZXM
      project-id: '001'
      email: c_qingyun2002@163.com